algoritmo "Algoritmo CalculoQuadrado"
          "Cap03_Ex3i_Pg057"
//Efetuar a leitura de um valor numérico inteiro  e apresentar o resultado
//do valor lido elevado ao quadrado.
 var
Numero, Quadrado: Inteiro
 inicio
 
 Escreval("Digite um numero inteiro: ")
 
   Leia(Numero)

   Quadrado <- Numero * Numero
   //Quadrado <- Numero ^ 2

   Escreval("O numero elevado ao quadrado é: ", Quadrado)
fimalgoritmo
